# ABHISHEK KUMAR 20MAI0005

In [44]:
#Importing necessary libraries for dataframe manipulation
# Import the numpy , pandas and sklearn packages

import pandas as pd
import numpy as np
import sklearn.datasets

In [45]:
#Importing the Dataset Sklearn
# Read the file
cancer_ds = sklearn.datasets.load_breast_cancer()
cancer_ds

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [46]:
#Organising data into x and y
X=cancer_ds.data
Y=cancer_ds.target

In [47]:
#Print the value of X & Y
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [48]:
#Printing number of records in dataset using shape
print(X.shape,Y.shape)

(569, 30) (569,)


In [49]:
#Importing necessary libraries for dataframe manipulation
import pandas as pd
#Getting data into a dataframe
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names)

In [50]:
# Check the column-wise info of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [51]:
# Check the number of rows and columns in the dataframe

data.shape

(569, 30)

In [52]:
#remain the y variable as target
data['class']= cancer_ds.target

In [53]:
#examine the first few records
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [54]:
#Sanity Check
data.describe()
# Get a summary of the dataframe using 'describe()'

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [55]:
# Get the column-wise Null count using 'is.null()' alongwith the 'sum()' function
data.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
class                      0
dtype: int64

In [56]:
#how many malignant and benign?
data['class'].value_counts()#binary variable

1    357
0    212
Name: class, dtype: int64

In [57]:
print(cancer_ds.target_names)

['malignant' 'benign']


In [58]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

In [59]:
data.groupby('mean area').mean()

mean radius  mean texture  mean perimeter  mean smoothness  \
mean area                                                               
143.5            6.981         13.43           43.79          0.11700   
170.4            7.691         25.44           48.34          0.08668   
178.8            7.729         25.49           47.98          0.08098   
181.0            7.760         24.54           47.92          0.05263   
201.9            8.196         16.84           51.71          0.08600   
...                ...           ...             ...              ...   
1878.0          25.220         24.91          171.50          0.10630   
2010.0          25.730         17.46          174.20          0.11490   
2250.0          27.220         21.87          182.10          0.10940   
2499.0          28.110         18.47          188.50          0.11420   
2501.0          27.420         26.27          186.90          0.10840   

           mean compactness  mean concavity  mean concave points  \
mean area                                                          
143.5               0.07568         0.00000             0.000000   
170.4               0.11990         0.09252             0.013640   
178.8               0.04878         0.00000             0.000000   
181.0               0.04362         0.00000             0.000000   
201.9               0.05943         0.01588             0.005917   
...                     ...             ...                  ...   
1878.0              0.26650         0.33390             0.184500   
2010.0              0.23630         0.33680             0.191300   
2250.0              0.19140         0.28710             0.187800   
2499.0              0.15160         0.32010             0.159500   
2501.0              0.19880         0.36350             0.168900   

           mean symmetry  mean fractal dimension  radius error  ...  \
mean area                                                       ...   
143.5             0.1930                 0.07818        0.2241  ...   
170.4             0.2037                 0.07751        0.2196  ...   
178.8             0.1870                 0.07285        0.3777  ...   
181.0             0.1587                 0.05884        0.3857  ...   
201.9             0.1769                 0.06503        0.1563  ...   
...                  ...                     ...           ...  ...   
1878.0            0.1829                 0.06782        0.8973  ...   
2010.0            0.1956                 0.06121        0.9948  ...   
2250.0            0.1800                 0.05770        0.8361  ...   
2499.0            0.1648                 0.05525        2.8730  ...   
2501.0            0.2061                 0.05623        2.5470  ...   

           worst texture  worst perimeter  worst area  worst smoothness  \
mean area                                                                 
143.5              19.54            50.41       185.2           0.15840   
170.4              31.89            54.49       223.6           0.15960   
178.8              30.92            57.17       248.0           0.12560   
181.0              30.37            59.16       268.6           0.08996   
201.9              21.96            57.26       242.2           0.12970   
...                  ...              ...         ...               ...   
1878.0             33.62           211.70      2562.0           0.15730   
2010.0             23.58           229.30      3234.0           0.15300   
2250.0             32.85           220.80      3216.0           0.14720   
2499.0             18.47           188.50      2499.0           0.11420   
2501.0             31.37           251.20      4254.0           0.13570   

           worst compactness  worst concavity  worst concave points  \
mean area                                                             
143.5                0.12020           0.0000               0.00000   
170.4                0.30640           0.3393               0.0

# Train Test Split

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
X = data.drop('class',axis=1)
Y = data['class']

In [62]:
#magical line of code to split
# Splitting dataset into 90% for training and 10% of testing
X_train, X_test ,Y_train, Y_test = train_test_split(X,Y,test_size=0.1, stratify = Y ,random_state=0)

In [63]:
#Number of records in Y, Y_train, Y_test
print(Y.shape,Y_train.shape,Y_test.shape)

(569,) (512,) (57,)


In [64]:
#Number of records in X, X_train, X_test
print(X.shape ,X_train.shape,X_test.shape)

(569, 30) (512, 30) (57, 30)


In [65]:
print(Y.mean(), Y_train.mean(),Y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421


In [66]:
print(X.mean(), X_train.mean(),X_test.mean())

mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [67]:
#binarization of input
X_binarised_train = X_train.apply(pd.cut , bins=2,labels=[1,0])
X_binarised_test = X_test.apply(pd.cut,bins=2, labels=[1,0])


In [68]:
#converting into array type
X_binarised_train = X_binarised_train.values
X_binarised_test = X_binarised_test.values


In [69]:
type( X_binarised_train)

numpy.ndarray

In [70]:
b = 10 #threshold value
from random import randint

i=randint(0,X_binarised_train.shape[0])

if(np.sum(X_binarised_train[i,:])>=b):
    print('Model prediction is Malignant')
else:
    print('Model prediction is Bengin')

if(Y_train[i]==1):
    print('Actual outcome is Malignant')
else:
    print('Actual outcome is Bengin')

Model prediction is Malignant
Actual outcome is Bengin


In [71]:
# Training the model and predicting the accuracy of Trained data
accurate_rows = 0

for x,y in zip(X_binarised_train, Y_train):
    y_pred = (np.sum(x)>=b)
    accurate_rows += (y == y_pred)
    
print(accurate_rows, accurate_rows/X_binarised_train.shape[0])  #Displaying the number correctly predicted rows and Accuracy score

321 0.626953125


In [72]:
print("Training")
from random import randint

#i=randint(0,X_binarised_train.shape[0])
i=100
for b in range (X_binarised_train.shape[1]+1):
    accurate_rows =0

    for x,y in zip(X_binarised_train, Y_train):
        y_pred=(np.sum(x)>=b)
        accurate_rows +=(y == y_pred )
    
    print("For b = ", b,accurate_rows,accurate_rows/X_binarised_train.shape[0])

Training
For b =  0 321 0.626953125
For b =  1 321 0.626953125
For b =  2 321 0.626953125
For b =  3 321 0.626953125
For b =  4 321 0.626953125
For b =  5 321 0.626953125
For b =  6 321 0.626953125
For b =  7 321 0.626953125
For b =  8 321 0.626953125
For b =  9 321 0.626953125
For b =  10 321 0.626953125
For b =  11 321 0.626953125
For b =  12 321 0.626953125
For b =  13 322 0.62890625
For b =  14 325 0.634765625
For b =  15 328 0.640625
For b =  16 329 0.642578125
For b =  17 333 0.650390625
For b =  18 338 0.66015625
For b =  19 340 0.6640625
For b =  20 347 0.677734375
For b =  21 356 0.6953125
For b =  22 369 0.720703125
For b =  23 383 0.748046875
For b =  24 400 0.78125
For b =  25 418 0.81640625
For b =  26 430 0.83984375
For b =  27 433 0.845703125
For b =  28 438 0.85546875
For b =  29 408 0.796875
For b =  30 346 0.67578125


In [73]:
print("Testing:")
#from random import randint

#i=randint(0,X_binarised_train.shape[0])
i=100
for b in range (X_binarised_test.shape[1]+1):
    accurate_rows =0

    for x,y in zip(X_binarised_test, Y_test):
        y_pred=(np.sum(x)>=b)
        accurate_rows +=(y == y_pred )
    
    print("For b = ", b,accurate_rows,accurate_rows/X_binarised_test.shape[0])    

    


Testing:
For b =  0 36 0.631578947368421
For b =  1 36 0.631578947368421
For b =  2 36 0.631578947368421
For b =  3 36 0.631578947368421
For b =  4 36 0.631578947368421
For b =  5 36 0.631578947368421
For b =  6 36 0.631578947368421
For b =  7 37 0.6491228070175439
For b =  8 37 0.6491228070175439
For b =  9 37 0.6491228070175439
For b =  10 37 0.6491228070175439
For b =  11 37 0.6491228070175439
For b =  12 37 0.6491228070175439
For b =  13 38 0.6666666666666666
For b =  14 40 0.7017543859649122
For b =  15 40 0.7017543859649122
For b =  16 41 0.7192982456140351
For b =  17 42 0.7368421052631579
For b =  18 42 0.7368421052631579
For b =  19 44 0.7719298245614035
For b =  20 46 0.8070175438596491
For b =  21 48 0.8421052631578947
For b =  22 49 0.8596491228070176
For b =  23 50 0.8771929824561403
For b =  24 50 0.8771929824561403
For b =  25 50 0.8771929824561403
For b =  26 47 0.8245614035087719
For b =  27 46 0.8070175438596491
For b =  28 42 0.7368421052631579
For b =  29 35 0.61403

In [74]:
#found that for b value of 27 and 28 high accuracy in training and predicting the test data
b=27
accurate_rows = 0
for x,y in zip(X_binarised_test, Y_test):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
print("For b =",b, accurate_rows, accurate_rows/X_binarised_train.shape[0])

b=28
accurate_rows = 0
for x,y in zip(X_binarised_test, Y_test):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
print("For b =",b, accurate_rows, accurate_rows/X_binarised_train.shape[0])

For b = 27 46 0.08984375
For b = 28 42 0.08203125


In [75]:
# Splitting dataset into 70% for training and 30% of testing
X_train1,X_test1,Y_train1,Y_test1 = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=0)

In [76]:
#Number of records in Y, Y_train, Y_test
print(Y.shape,Y_train1.shape,Y_test1.shape)

(569,) (398,) (171,)


In [77]:
print(Y.mean(),Y_train1.mean(),Y_test1.mean())

0.6274165202108963 0.628140703517588 0.6257309941520468


In [78]:
#Number of records in X, X_train, X_test
print(X.shape,X_train1.shape,X_test1.shape)

(569, 30) (398, 30) (171, 30)


In [79]:
print(X.mean(),X_train1.mean(),X_test1.mean())

mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [80]:
#Binarising the data
X_binarised_train = X_train1.apply(pd.cut, bins=2, labels=[1,0])
X_binarised_test = X_test1.apply(pd.cut, bins=2, labels=[1,0])
X_binarised_train = X_binarised_train.values    #converting into array type
X_binarised_test = X_binarised_test.values

In [81]:
# Training the model and predicting the accuracy of Trained data
print("Training")
for b in range(X_binarised_train.shape[1]+1):
    accurate_rows = 0

    for x,y in zip(X_binarised_train, Y_train1):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
        
    
    print("For b =",b, accurate_rows, accurate_rows/X_binarised_train.shape[0])

Training
For b = 0 250 0.628140703517588
For b = 1 250 0.628140703517588
For b = 2 250 0.628140703517588
For b = 3 250 0.628140703517588
For b = 4 250 0.628140703517588
For b = 5 250 0.628140703517588
For b = 6 250 0.628140703517588
For b = 7 250 0.628140703517588
For b = 8 250 0.628140703517588
For b = 9 250 0.628140703517588
For b = 10 250 0.628140703517588
For b = 11 250 0.628140703517588
For b = 12 251 0.6306532663316583
For b = 13 252 0.6331658291457286
For b = 14 252 0.6331658291457286
For b = 15 256 0.6432160804020101
For b = 16 258 0.6482412060301508
For b = 17 262 0.6582914572864321
For b = 18 265 0.6658291457286433
For b = 19 267 0.6708542713567839
For b = 20 272 0.6834170854271356
For b = 21 287 0.7211055276381909
For b = 22 295 0.7412060301507538
For b = 23 305 0.7663316582914573
For b = 24 315 0.7914572864321608
For b = 25 323 0.8115577889447236
For b = 26 333 0.8366834170854272
For b = 27 337 0.8467336683417085
For b = 28 337 0.8467336683417085
For b = 29 318 0.7989949748

In [82]:
# Testing the model and predicting the accuracy of Test data
print("Testing")
for b in range(X_binarised_test.shape[1]+1):
    accurate_rows = 0

    for x,y in zip(X_binarised_test, Y_test1):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
    
    print("For b =",b, accurate_rows, accurate_rows/X_binarised_test.shape[0])


Testing
For b = 0 107 0.6257309941520468
For b = 1 107 0.6257309941520468
For b = 2 107 0.6257309941520468
For b = 3 107 0.6257309941520468
For b = 4 107 0.6257309941520468
For b = 5 107 0.6257309941520468
For b = 6 107 0.6257309941520468
For b = 7 107 0.6257309941520468
For b = 8 107 0.6257309941520468
For b = 9 107 0.6257309941520468
For b = 10 108 0.631578947368421
For b = 11 109 0.6374269005847953
For b = 12 109 0.6374269005847953
For b = 13 109 0.6374269005847953
For b = 14 112 0.6549707602339181
For b = 15 113 0.6608187134502924
For b = 16 116 0.6783625730994152
For b = 17 118 0.6900584795321637
For b = 18 120 0.7017543859649122
For b = 19 120 0.7017543859649122
For b = 20 122 0.7134502923976608
For b = 21 130 0.7602339181286549
For b = 22 134 0.783625730994152
For b = 23 141 0.8245614035087719
For b = 24 150 0.8771929824561403
For b = 25 149 0.8713450292397661
For b = 26 150 0.8771929824561403
For b = 27 153 0.8947368421052632
For b = 28 151 0.8830409356725146
For b = 29 133 0.7

In [83]:
#found that for b value of 27 and 28 high accuracy in training and predicting the test data
b=27
accurate_rows = 0
for x,y in zip(X_binarised_test, Y_test1):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
print("For b =",b, accurate_rows, accurate_rows/X_binarised_test.shape[0])

b=28
accurate_rows = 0
for x,y in zip(X_binarised_test, Y_test1):
        y_pred = (np.sum(x)>=b)
        accurate_rows += (y == y_pred)
print("For b =",b, accurate_rows, accurate_rows/X_binarised_test.shape[0])

For b = 27 153 0.8947368421052632
For b = 28 151 0.8830409356725146


# Conclusion:

After training the data we have seen that for a threshold value of b=27 and b=28 found high accuracy. So we went for testing data with threshold value of 27 and 28 and found that accuracy score was near to the train data accuracy. The above model was split twice, one model was split into 90-10% and other was split into 70-30%. The model split into 70-30% has higher accuracy than the first model.Therefore with this we can conclude that our model predicted correctly.